spring:
  application:
    name: gateway

  cloud:
    gateway:
      mvc:
        routes:

          - id: example-route
            uri: http://resourceserver:8080/
            predicates:
              - Path=/api/**


          - id: jokes-route
            uri: http://jokeservice:8080/
            predicates:
              - Path=/jokes/**



          - id: quotes-route
            uri: http://quoteservice:8082/
            predicates:
              - Path=/quotes/**



          - id: auth-login-route
            uri: http://auth:9000/
            predicates:
              - Path=/auth/token
            filters:
              - RewritePath=/auth/token, /oauth2/token

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth:9000

server:
  port: 8081
